# Generated by Django 2.0.2 on 2018-02-24 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mythought',
            name='bloggerr',
        ),
        migrations.AddField(
            model_name='mythought',
            name='blogger',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
