# Generated by Django 2.0.2 on 2018-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180224_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythought',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
