# Generated by Django 2.0.2 on 2018-02-20 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20180221_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentblog',
        ),
    ]
