# Generated by Django 2.0.2 on 2018-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180221_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_author', models.CharField(max_length=400, null=True)),
                ('strong', models.CharField(max_length=40)),
            ],
        ),
    ]
