# Generated by Django 2.0.2 on 2018-02-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_mythought_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='description',
            new_name='descriptions',
        ),
    ]
