# Generated by Django 2.0.2 on 2018-02-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180222_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
