# Generated by Django 2.0.2 on 2018-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180222_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readarticle',
            name='document',
        ),
        migrations.AddField(
            model_name='article',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
