# Generated by Django 2.0.2 on 2018-02-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180222_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readarticle',
            name='views',
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
