# Generated by Django 2.0.2 on 2018-02-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180222_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
