# Generated by Django 2.0.2 on 2018-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_author_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='long_description',
        ),
        migrations.AddField(
            model_name='author',
            name='longdescription',
            field=models.TextField(null=True),
        ),
    ]
