# Generated by Django 2.0.2 on 2018-02-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180223_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='longdescription',
            new_name='description',
        ),
    ]
